### ISSUE TITLE
Multi Process for Centaury

### ISSUE THREAD

**Issue by andika207** [Feodor2/Centaury#11]
is there any possibility to unlock the multi process mode on the Centaury browser ?
it's almost impossible to surf on heavy-load sites such as facebook because it freezes easily
the only XP compatible browser that works pretty much is the **Serpent**, everything else is pure junk including the Chinese forks of chrome.

**Comment by Feodor2** [comment]
No, and no any point to do this. Take firefox 52 where the possibility exists.

Can you name any other heavy-load freezer site beside facepuk?

**Comment by andika207** [comment]
> 
> 
> No, and no any point to do this. Take firefox 52 where the possibility exists.
> 
> Can you name any other heavy-load freezer site beside facepuk?

Yes Firefox 52 with multi process runs very smooth but it's not been updated for years and some sites don't work anymore.
why don't you unlock the multi process ? do you think people who use XP only have crap old hardware with single core CPU ?
it's ok if you want to keep up the MyPal browser for poor computers but there is no reason to have two browsers with the same defect.

**Comment by Feodor2** [comment]
If it will be any actual proof that multiprocess is better i would be happy to recover it. I can make research on core2due with 4gb ram, though on winxp 3gb is available.

**Comment by andika207** [comment]
> 
> 
> If it will be any actual proof that multiprocess is better i would be happy to recover it. I can make research on core2due with 4gb ram, though on winxp 3gb is available.

No it's not better, it's so much better. 
Depending on your motherboard you can get 4GB up to 128GB of RAM with an unofficial PAE patch. 
http://rutracker.org/forum/viewtopic.php?t=4694409

**Comment by Feodor2** [comment]
>it's so much better.

This is not a proof at all, the link is irrelevent too.

Well i shall take two copies of the firefox 52 one set to multiprocess and surf same sites to see the difference. But all i heard before that multiprocess is useless and i not eager to make a research so when i going to do this i wont say. I asked if you can point to some informations that make encourage me make research soon also i think others was investigating this too.

**Comment by andika207** [comment]
''This is not a proof at all, the link is irrelevent too.''

if the multi process is useless for you why do you think firefox and chrome developers have invented it ? just for fun ?

**Comment by andika207** [comment]
**''This is not a proof at all, the link is irrelevent too.''**

if the multi process is useless for you why do you think firefox and chrome developers have invented it ? just for fun ?

**Comment by andika207** [comment]
**''Well i shall take two copies of the firefox 52 one set to multiprocess and surf same sites to see the difference.''**

why do you need to hear from others ? in 2020 are you still using a single core CPU or what ? 
when I switched from a 2 core over to 4 core CPU the performance gain was like day and night so just imagine what the multiprocess con do on web browsers.

**Comment by andika207** [comment]
**''I asked if you can point to some informations that make encourage me make research soon also i think others was investigating this too.''**

not sure I understand what you mean, but the multiprocess should be available for people who want to use it, if you fell it's unnecessary then don't use it, it's simple as that. 
on Firefox 52 or Serpent 52 the multiprocess is disabled by default but many people use it for performance reasons.

**Comment by Feodor2** [comment]
Do you want me begin to do something for recovering multiprocess soon? Provide the proof that it really has better performance in terms firefox usage on winxp. Others maybe have completed research. Otherwise i shall be making it myself when i have the mood do not know actually when.

Next you are to get that i do reason to favor lowend comps and do not care about modern comps.

**Comment by Feodor2** [comment]
https://forum.palemoon.org/viewtopic.php?f=26&t=17442&p=127695

that makes no favor.

**Comment by andika207** [comment]
**''Next you are to get that i do reason to favor lowend comps and do not care about modern comps.''**

modern computers ?
I own i5 and i7 hardware but my Main PC that I use 99% of the time has a ASUS mainboard and AMD X4 released **before 2010**...
I have tried out all those browsers for XP Firefox 27, Newmoon 28, Articfox, Mypal, KMeleon ...etc they are all the same Junk 
the best one is the Serpent 52 with multiprocess enabled followed by the deprecrated Firefox 52 with multiprocess
are you still using a single core CPU in 2020 ?

**Comment by andika207** [comment]
> 
> 
> https://forum.palemoon.org/viewtopic.php?f=26&t=17442&p=127695
> 
> that makes no favor.

I won't read that shit, I just read who the poster is to understand everything.
if someone been stuck on Firefox 28 for ages and doesn't want to go forward it's normal that every thing for him is not useful.
I have also tested his Basilisk browser on Windows 7 and it's not better than Firefox or any chromium based browser.

**Comment by Feodor2** [comment]
I told you that i have cor2duo why do keep asking again.
I suspect you are not able to provide the proof, so you have to wait. One day... one day....
If you like the Serpent than take it and use, it almost the same

**Comment by Feodor2** [comment]
By the way this browser and your so loved Serpent base on the Basilisk.
Mypal and Palemoon based on the same code too only have oldstyle interface

**Comment by andika207** [comment]
> 
> 
> I told you that i have cor2duo why do keep asking again.
> I suspect you are not able to provide the proof, so you have to wait. One day... one day....
> If you like the Serpent than take it and use, it almost the same

You told me you had to do some research with a C2D but I didn't know that it was your CPU
if you were living near me I could offer you better hardware for free that I don't use

**Comment by andika207** [comment]
> 
> 
> I told you that i have cor2duo why do keep asking again.
> I suspect you are not able to provide the proof, so you have to wait. One day... one day....
> If you like the Serpent than take it and use, it almost the same

you can suspect as much as you want but your opinions are based on the shit you read on the internet from old man with crap hardware that are still running Windows 2000
Yes I know this is a fork of Basilisk but **without multi process function**
I have already told you that the original Basilisk on W7 is pure junk compared to other browsers with multi process.
Stop reading shit on the internet and buy a quad core CPU, you will immediately feel a huge performance difference

**Comment by mattatobin** [comment]
Btw, we has to ban this person for spamming the issue tracker of one of mcp projects, I highly suggest you do the same @Feodor2

**Comment by wolfbeast** [comment]
> By the way this browser and your so loved Serpent base on the Basilisk.
Mypal and Palemoon based on the same code too only have oldstyle interface

It's sad that you don't know shit about the code you're using.

**Comment by andika207** [comment]
@mattatobin -first, you didn't reply to the post in which you got ridiculed by stating that Basilisk is not based on Firefox 52, if it's only based on FF 28 why don't you edit the UXL website ?
https://github.com/mindedsecurity/behave/issues/17#issuecomment-664178319

-second, it's not that I don't accept a NO as an answer but time has proven you are a liar because Basilisk doesn't have the multi process mode enabled because you don't want not because this feature is not available in any UXP application

-third, you are just a fat dictator hidden behind a computer that deletes my posts for no apparent reason, maybe because I wrote SERPENT and that makes you feel bad... and Yes the Serpent @roytam1 with multi process enabled performs a lot better than the Basilisk browser. https://github.com/MoonchildProductions/Basilisk/issues/25#issuecomment-663821909

-fourth, we know you hate XP but please stop trolling and posting shit on other groups @Feodor2 in order to attack me. https://github.com/Feodor2/Centaury/issues/11#issuecomment-663972900

-fifth if you are enough man you should not call your dogs @wolfbeast for help or is it you with multiple accounts ?
I have not read this shit I use my computers to test it myself and can confirm that multi process is a must whatever you say
https://forum.palemoon.org/viewtopic.php?f=26&t=17442&p=127695

**Comment by wolfbeast** [comment]
> Yes the Serpent @roytam1 with multi process enabled

Have fun getting hacked. Unless of course roytam1 has personally addressed all the sec issues that exist in e10s that makes up 75% or more of every Firefox release cycle sec bugs?
Because they for sure are not considered for UXP development.

And I can assure you I am not Tobin. Everyone with half an inch of involvement in anything knows that :D

**Comment by mattatobin** [comment]
I thought you and @roytam1 's users never confuse MCP and BinOC projects with your builds. I thought your users knew never to come to us, I thought your users weren't going to cause issues for us.

@Feodor2 you and roytam1 said that this never happens nor would ever happen. I was merely unreasonable or lying. So if true, what do you call this?

**Comment by Feodor2** [comment]
So you want to spam much... continue further and be here rewarded with ban too.

**Comment by andika207** [comment]
@Feedor2
