### ISSUE TITLE
can't choose other search engines

### ISSUE THREAD

**Issue by muzungumwiza** [Feodor2/Centaury#22]
Hi,
When trying to "add more search engines..." there is an error - the link seems to be broken. I'd like to set Google as default search. thanks

**Comment by Feodor2** [comment]
Yea the link is to be fixed. It will be https://mycroftproject.com/search-engines.html

**Comment by muzungumwiza** [comment]
THANK YOU very much!

     Le lundi 18 janvier 2021 à 11:56:26 UTC+1, Feodor2 <notifications@github.com> a écrit :  
 
 


Yea the link is to be fixed. It will be https://mycroftproject.com/search-engines.html
