### ISSUE TITLE
Centaury on other OS

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [Feodor2/Centaury#24]
Is centaury can be used on win10? any chance to compile on MacOSX and Linux?
also flash player can be installed for long term?
thanks

**Comment by StefCraps** [comment]
> Is centaury can be used on win10? any chance to compile on MacOSX and Linux?
> also flash player can be installed for long term?
> thanks

Haha why the hell u need centaury on windows 10 i have xp and i need centaury on xp but u? u have windows 10 cmon man install something modern like cent browser is pretty cool i was using it 2 years without problem

**Comment by ROBERT-MCDOWELL** [comment]
@StefCraps
first of all try to have a little respectful non childish behavior when you comment here.
secondly, I have my good reasons to do it and it's my problem, not yours.

**Comment by StefCraps** [comment]
> @StefCraps
> first of all try to have a little respectful non childish behavior when you comment here.
> secondly, I have my good reasons to do it and it's my problem, not yours.

I just wanted to help u if i give u advice and telling u to use something modern it means i'm childish? cmon man stop typing craaap

**Comment by ROBERT-MCDOWELL** [comment]
@StefCraps
if you don't understand how to respect people, I can't help you.
in a normal society wiwth conscious people, when someone needs help, he/she just asks help.
but someone coming, forcing people with stupid words like "c'mon don't be fooled use modern browser" is no more than a fascist stupid behavior.l I never asked help, especially when you have 35 years of computer experience, and I called childish your behavior, nothing else. so now case closed,

**Comment by StefCraps** [comment]
> @StefCraps
> if you don't understand how to respect people, I can't help you.
> in a normal society wiwth conscious people, when someone needs help, he/she just asks help.
> but someone coming, forcing people with stupid words like "c'mon don't be fooled use modern browser" is no more than a fascist stupid behavior.l I never asked help, especially when you have 35 years of computer experience, and I called childish your behavior, nothing else. so now case closed,

Do what u want i don't give a shiit about u or about ur fuqin comp or about ur fuqin browsers and aslo fuq ur mother

**Comment by ROBERT-MCDOWELL** [comment]
yeah good answer, GFY and bye.

**Comment by StefCraps** [comment]
> GFY

GO FUCK UR MOTHER BLOCKED

**Comment by Feodor2** [comment]
The last waring StefCraps, next will be a ban

**Comment by StefCraps** [comment]
> The last waring StefCraps, next will be a ban

Tell it to robert he started all this craaap not me sroll up and read what he wrote me when i gave him some advice
