### ISSUE TITLE
Cannot make a post at forum.ixbt.com

### ISSUE THREAD

**Issue by lokapal** [Feodor2/Centaury#25]
While trying to make a post at forum.ixbt.com the following window reappears permanently:
![post](https://user-images.githubusercontent.com/6469161/106354850-9f16f400-6305-11eb-8f2f-1b1dff1ab68d.png)
independently from any keys pressed at this window.
Original Basilisk works without any problems. Are there any advice about about:config? Right now 
general.useragent.compatMode.firefox;true
general.useragent.compatMode.gecko;true
general.useragent.override.forum.ixbt.com;Mozilla/5.0 (%OS_SLICE% rv:62.0) Gecko/20100101 Firefox/62.0
general.useragent.override.ixbt.com;Mozilla/5.0 (%OS_SLICE% rv:62.0) Gecko/20100101 Firefox/62.0

And yes, it doesn't depend upon any addons/plugins - in the safe mode the behaviour is quite the same

**Comment by AroKol78** [comment]
Original Basilisk **68**, not 62
what system (Windows NT 6.3 = win8.1 try this)
`Mozilla/5.0 (Windows NT 6.3; WOW64; rv:68.0) Gecko/20100101 Firefox/68.0`
you can even set a larger number than 68, for example 78,...
(I would have helped more but completely does not understand the site)

**Comment by lokapal** [comment]
Nothing changed, 'course, the same window appears, the same result. I guess it is the problem with restored/XP functionality (yes, I've tried to turn OFF multiprocessing, nothing changed).

**Comment by AroKol78** [comment]
> turn OFF multiprocessing
```
browser.tabs.remote.autostart         false
browser.tabs.remote.autostart.1       false
browser.tabs.remote.autostart.2       false
browser.tabs.remote.force-enable      false
browser.tabs.remote.force-disable     true
```

**Comment by lokapal** [comment]
Firefox 52.9.1 x64 ESR can post to this forum without slightest problems with multiprocessing turned ON
(from FF config):
browser.tabs.remote.autostart;true
browser.tabs.remote.autostart.2;true
browser.tabs.remote.desktopbehavior;true
browser.tabs.remote.force-enable;true

**Comment by AroKol78** [comment]
Restore multiprocess in Centaury ,code - https://github.com/Feodor2/Mypal/commit/cdf6b759c0fdc14bb06ab0781671a6f019c3ab38

**Comment by lokapal** [comment]
Nope, it doesn't help - the same window, the same behaviour.

**Comment by AroKol78** [comment]
maybe try roytam1 browser Serpent/UXP for XP from `https://rtfreesoft.blogspot.com/`

**Comment by lokapal** [comment]
From Basilisk original config:
javascript.options.wasm;true
javascript.options.wasm_baselinejit;true

Basilisk can post with no problems. The difference is between Basilisk original 2021.01.05 and Centaury 2021.01.21. The profile in Centaury is Basilisk profile copied fully

**Comment by AroKol78** [comment]
don't compare the browser 1:1
Feodor2 - use custom codes for XP

**Comment by lokapal** [comment]
BTW, latest Serpent x64 can't post to forum.ixbt.com too.
