### ISSUE TITLE
Cannot open https://discuss.ott.blue/ at all even in the safe mode

### ISSUE THREAD

**Issue by lokapal** [Feodor2/Centaury#26]
see subj - Centaury X64 cannot open https://discuss.ott.blue/ at all even in the safe mode. Permanently banner
"Checking your browser before accessing ott.blue.

Please enable Cookies and reload the page.

This process is automatic. Your browser will redirect to your requested content shortly.

Please allow up to 5 seconds…"
is hanging...

**Comment by Feodor2** [comment]
Last centaury - not confirmed, works as expected, someone else please check.
