### ISSUE TITLE
SVG images does not show after updating to 0.16

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [Feodor2/Centaury#32]
SVG images does not show after updating to 0.16
do I need to do something special?
thanks

**Comment by Feodor2** [comment]
Yes, i have added new setting about from tor but missed put its value sorry
open about:config and add new boolean setting **svg.in-content.enabled;true**

**Comment by ROBERT-MCDOWELL** [comment]
ha ok, so I can update it again so ;) thanks

**Comment by ROBERT-MCDOWELL** [comment]
mmhm, there is no  svg.in-content.enabled settings in about:config :(

**Comment by Feodor2** [comment]
>there is no svg.in-content.enabled settings in about:config

yes, you have been told so another words, add new setting and it will be

**Comment by ROBERT-MCDOWELL** [comment]
oops, I didn't see "add" :)
