### ISSUE TITLE
 Instagram and youtube websites won't work after upgrading to 0.16.0

### ISSUE THREAD

**Issue by kwisomialbert** [Feodor2/Centaury#33]
I downgraded to 0.15.0 and it works again.

**Comment by kwisomialbert** [comment]
![2021-05-09_223250](https://user-images.githubusercontent.com/75623042/117588114-51d2cb80-b119-11eb-98fc-a17438ea49af.jpg)
![2021-05-09_223244](https://user-images.githubusercontent.com/75623042/117588124-5e572400-b119-11eb-9db7-a548ba0dbdb4.jpg)

**Comment by Feodor2** [comment]
look for #32

**Comment by kwisomialbert** [comment]
Thanks a lot
