### ISSUE TITLE
CSS issue

### ISSUE THREAD

**Issue by gdl-888** [Feodor2/Centaury#35]
CSS color values something like `hsl(139, calc(0.5 * 47.3%), 43.9%)` throws invalid. Sites like Discord uses this kind of values. This value is valid in Chrome 49, and newer Chrome, Firefox Quantum. Actually this issue does not only happen in Centaury but also in Mypal, and other legacy Firefox-based browsers(Seamonkey 2.49.5, Firefox 52.9.0 ESR, Bollaris Navigator, Serpent, etc)

![image](https://user-images.githubusercontent.com/55873929/126101414-f49fbc2d-d867-4dc2-bc2f-4f6ff4b371c0.png)
![image](https://user-images.githubusercontent.com/55873929/126101366-159253f4-f2de-4210-8a6d-74f8543a562e.png)

**Comment by Feodor2** [comment]
Noted try to fix
