### ISSUE TITLE
Mozilla Public License violation.

### ISSUE THREAD

**Issue by athenian200** [Feodor2/Centaury#40]
Hello, it has come to my attention that you are using code from a project to which I have contributed to in the past, but I cannot seem to find the `Source Code Form` nor any information on how to obtain it. Please be aware that this is a violation of the `Mozilla Public License`. To wit,

```
Section 1.13
means the form of the work preferred for making modifications.
```

```
Section 3.2 (a)
such Covered Software must also be made available in Source Code Form,
as described in Section 3.1, and You must inform recipients of the
Executable Form how they can obtain a copy of such Source Code
Form by reasonable means in a timely manner, at a charge no more
than the cost of distribution to the recipient;
```

**Comment by Feodor2** [comment]
https://github.com/Feodor2/Mypal/tree/Centaury_Release

will you able to obtain it from there?

**Comment by ghost** [comment]
I do appreciate the link, but I'm afraid it doesn't quite solve the problem. The main one is that there don't appear to be releases of the specific source code used to build a particular version. So while that may be the base on which each version is built, there's no obvious means to reproduce the version of the code used to build each of the executable forms of Centaury being distributed.

Notice that on the MyPal repo, they include the source code used to build _each_ release of MyPal in a tar.gz that release. There are also tags in that repo pointing to the code used to build each version. But with Centaury, that's definitely not the case. While there are indeed tar.gz files alongside each release of Centaury, they do not contain the source code used to build it. There are also no tags for specific release versions of Centaury in the MyPal repo, just a branch for the latest release. So I could maybe reproduce the latest Centaury with that link, but I couldn't reproduce the past versions of the executable you've released previously.

I assure you this is nothing personal, it's a matter of principle. If I permit you to violate the license agreement, then that undermines the system of international copyright law upon which both open source projects and proprietary ones depend, and it creates an anarchic environment of distrust that discourages software developers from contributing any code at all to any project.

**Comment by Feodor2** [comment]
You can use the source code link for building any version, where license requirements about to put it on the tag along?

**Comment by ghost** [comment]
> You can use the source code link for building any version, where license requirements about to put it on the tag along?

Let me try to explain it this way...

Suppose I wanted an exact copy of the source code used to build Centaury 0.14.0. How would I use the provided source code link to build that particular version? In that branch you linked, I only see the code that was used to build the latest version, 0.17.0. Can you document the procedure people should follow in order to reproduce a copy of 0.14.0?

My point is, you have to keep the code for previous releases available, it's not sufficient to provide source code for _only_ the latest release, and as far as I can tell that is what you're doing.

**Comment by Feodor2** [comment]
All versions and commits have date of the release, you scroll down commits to older and the first commit near to the version date will be point to this version source code.
0.14.0  -   Nov 27, 2020
Commits on Nov 27, 2020
https://github.com/Feodor2/Mypal/commits/Centaury_Release?before=b9d3b502ef4786aa77d30e9ace63494422fa00a4+175&branch=Centaury_Release

**Comment by ghost** [comment]
Well, this is getting closer to what I'm asking for. So what you're saying is that if I build against the last commit on November 27th, 2020... which was "[Centaury] Apply libjar improvements." then I should be able to exactly reproduce version 0.14.0?

Okay, then what I'd like you to do is this... find the specific commit you built each version of Centaury against in the past, list them out somewhere publicly accessible, and link the list plus include instructions for how to reset git to a particular release commit on the front page, like you've done for how to checkout the latest source code.

**Comment by 0strodamus** [comment]
Why don't you get the troll that sent you here to perform the same actions regarding Interlink's source code?

**Comment by ghost** [comment]
I'm terribly sorry, but I lack the authorization to share Interlink's source code with you. I've signed a non-disclosure agreement with Binary Outcast as part of the process of becoming a volunteer and contributor. You would have to e-mail support@binaryoutcast.com and request a copy of the portions covered under the Mozilla Public License. Those portions can be provided for any version you wish upon request, though unfortunately the request would likely not be granted to anyone who has violated the Mozilla Public License in the past. 

If you feel that you potentially have a legal case against Binary Outcast, then I would of course encourage you to contact support regarding our compliance to see if this can be resolved to your satisfaction, and then if you are not satisfied with the outcome, to seek legal counsel and pursue the matter further. The law is the law, and I believe it must always be placed above personal loyalties.

 I notice you seem to have removed the offending executables. That should make compliance easier going forward. In the future, compliance should be easier if you keep the code in a separate repository and properly tag each release, or at least update a version number in the code itself somewhere so you can find the commit you built against more easily if you are asked to provide it. This is all I have to say, and I hope that you have a nice day.

**Comment by SeaHOH** [comment]
Compared with that, Tobin is sharp-tongued.

**Comment by JeanPaulLucien** [comment]
@athenian200 
Where did you find Executable Form? I have seen it never.
GH forbids publish software that maybe harmful.

**Comment by SeaHOH** [comment]
> Where did you find Executable Form? I have seen it never.

Seems had been deleted.

> GH forbids publish software that maybe harmful.

And where is the notification?
