### ISSUE TITLE
MPL 2.0 violation

### ISSUE THREAD

**Issue by wolfbeast** [Feodor2/Centaury#41]
Hello, it has come to my attention that you are using code from a project I founded and have significant investment in, in terms of authored code that is released under the Mozilla Public License 2.0 (MPL), for which you are in non-compliance in terms of providing the Source Code Form or any information on how to obtain it in such Source Code Form.

As a reminder, from the licence:

> Section 1.13
**Source Code Form** means the form of the work preferred for making modifications.

> Section 3.2 (a)
such Covered Software must also be made available in Source Code Form,
as described in Section 3.1, and You must inform recipients of the
Executable Form how they can obtain a copy of such Source Code
Form by reasonable means in a timely manner, at a charge no more
than the cost of distribution to the recipient;

To date, you have not provided the equivalent Source Code Form to the Executable Form you have released to the public. There are no available Source Code Forms for any Centaury releases as-published in its repo on which this issue was created (which contain only readme files), nor are they available from the redirection to the MyPal repo where there are no available Source Code Forms for Centaury either. Just pointing to a working branch in a live repository does not equal making the Source Code Form available.

Please be aware that this is a violation of the Mozilla Public License; this will have consequences for granted permission to use my authored code. Consider this my official one-time notification to come into compliance for my authored code.

**Comment by Feodor2** [comment]
>Redirection to the MyPal repo where there are no available Source Code Forms for Centaury either

Why it is not available, go look the https://github.com/Feodor2/Mypal/tree/Centaury_Release, you may download it and work preferred for making modifications.

**Comment by wolfbeast** [comment]
Really now? So, if I, say, wanted to get the Source Code Form for Centaury 0.13.0, where would I get it?

**Comment by Feodor2** [comment]
There are all versinos, do fit checkout

**Comment by wolfbeast** [comment]
Do `git checkout` of what, exactly?

> So, if I, say, wanted to get the Source Code Form for Centaury 0.13.0, where would I get it?

**Comment by Feodor2** [comment]
Scroll older commits and find last of the nearest date of that version (Commits on Oct 14, 2020)

**Comment by wolfbeast** [comment]
Yeah that's not how that works, Feodor.

> You must inform recipients of the Executable Form how they can obtain a copy of such Source Code Form by reasonable means in a timely manner

This is neither "by reasonable means" (because I'd have to guess which commit results in the correct Source Code Form), nor "in a timely manner" (because you didn't provide any accurate information when releasing the binaries). Although I _might_ be lenient to the latter if you didn't claim to be in the right and calling people liars who are just stating fact, the former is absolutely unacceptable. Telling people to check out a live tree and making them guess which is the right commit is not a reasonable way to obtain source code.
Fix source code access in an acceptable way or you'll find more people withdrawing your rights to using their authored code.

**Comment by Feodor2** [comment]
What a point, is see you wont leave me, if the actual violation license has happened this page will be shutdown and you stay happy with your precious.

**Comment by wolfbeast** [comment]
You seem to think this is something personal. It isn't. If you publish open source software you must comply with the license terms under which the source code was made available to you. That is a fact and that fact won't change based on your interpretation or opinion. As long as you are in violation I will indeed not leave it (or you) be because you are **legally required** to remain in compliance with the public license that allows you to use this code. Legally as in: "don't break the law". You understood that last time it was brought up so you'll understand it now.
I have nothing more to say on the matter. If you still don't believe me talk to a lawyer. Don't take my word for it.
