### ISSUE TITLE
GitHub authorization

### ISSUE THREAD

**Issue by saboteur1000** [Feodor2/Centaury#48]
А вы знаете, что с ваших браузеров не то что нельзя зайти в банк Открытие или, там, скажем, оставить коммент на YouTube, но даже нельзя залогиниться вот на этот самый сайт, где вы их выкладываете? Не правда ли, это иронично?
Я вот, к примеру, пишу с 360-го. Интересно, кто-нибудь ещё остался на MyPal или Centaury, и куда они с них умудряются заходить?

**Comment by StefCraps** [comment]
ia dumaiu shto nekto bolshe ne polzuietsa maypalam

**Comment by Feodor2** [comment]
https://github.com/Feodor2/Mypal/issues/12
