### ISSUE TITLE
Bring back the upper left close buton like all programs have for decades

### ISSUE THREAD

**Issue by spyrosmas** [Feodor2/Centaury#6]
That decision made by the firefox leaders and other shills who live in cavities and accept brain massage opposite to anything rational are bad and dishonest. Please brink back the good old left button in the program bar. Not all users have mobile devices or mobile bias in their brain. At least we can stay consistent with what we already have and only implement additional features or options that doesn't brake <b>consistence</b>.

**Comment by Feodor2** [comment]
I do not like australis too, use mypal mostly.
You can install classic theme restorer extension  if you want this particular browser with old design.

**Comment by spyrosmas** [comment]
Thanks, I install CTR_v1.7.8.2019.10.27.xpi from github and there is an option in their custom button "Classic Theme Restorer" who reads "Use Centaury titlebar instead of OS titlebar". Only then the standard system "close restore minimize etc" button is appear.

Even without Classic Theme Restorer addon installed if one hit Alt-Spacebar in his keyboard the system menu shows-up where the now hidden system (aka australis) button will be in the first place.

Anyway, I also use daily Mypal to surf within the corporate documentation crap or the how-to-forums who talk/help about corporate documentation crap :) and just play with Centaury because I can't disable-hide the Mustard yellowish youtube message who said: "We’ll stop supporting this browser soon. For the best experience please update your browser" with the Ublock Origin v1.16.4.16 "Block Element" feature. Maybe I have to add a custom rule there but I don't know that UO cryptic language to do so. So I rely on UO lists like Easylist etc. to cut some of the garbage who hog my screen, eat electricity and jamming ADSL line. Even then when I save a page the .js crap files in the _files folder are monstrous big. Then I have to go there to delete all those js files because the saved page (eg. an article) appears correctly even with offline mode enable in another browser.

**Comment by andika207** [comment]
@spyrosmas what button are you talking about ? post a screeshot please.

**Comment by spyrosmas** [comment]
![CTR default setting (double click does nothing)](https://user-images.githubusercontent.com/18444690/74113548-9c2f6a80-4bad-11ea-9b71-5474dab2db3c.png)
![CTR uncheck this to bring back double click](https://user-images.githubusercontent.com/18444690/74113550-a3567880-4bad-11ea-9b6f-50817534b949.png)
![CTR window system menu](https://user-images.githubusercontent.com/18444690/74113558-a9e4f000-4bad-11ea-8ca7-d34a37063340.png)
![Ublock Origin can't disable yellow message (right click - block element)](https://user-images.githubusercontent.com/18444690/74113797-288e5d00-4baf-11ea-82a4-b86b9337c8a0.png)
In the last screenshot the CTR is enabled and the OS style titlebar check button in the CTR preferences is unchecked so the Centaury window bar is as the OS commands (windows classic in my case, the themes service is also disable).
Anyway, that yellow youtube message doesn't go away with right click Ublock Origin -> Block element. My uploads are 1-to-1 screenshot images but github resize them because of github crap code or because I drag-drop them inside the text?

**Comment by andika207** [comment]
@spyrosmas I have never liked or used that upper left corner button so this is not an issue to me. I don't know why you do want to close your browser that way... 
do update your user agent with ''agent switcher addons'' this trick will bring you more performance and will likely work some issues out  https://www.youtube.com/?disable_polymer=true

**Comment by spyrosmas** [comment]
@andika207 _30 years ago till now_ all windows programs has the left system menu button because its **standard** and provided by the Operating System. Latest chrome and firefox applications just disable that system menu (**prove: alt-space is working**) some years before because their target market are mobiles and because they are despotic like all the corporation or institutions. Its not about personal likes or dislikes, its about policy and compatibility whom corporations mention only when they think they have some profit from it. See _The Corporation_ 2003 movie to elaborate on that subject. https://www.youtube.com/watch?v=Pin8fbdGV9Y

- eg1. The system supposed to used with a screen which has some standard controls so the UI is **consistent**. One may not "like" the screen and want to drop it because he is like to talk to a system rather than use the keyboard and/or the mouse; but that voice interaction is an extra feature or extension _to the system_. Thus a feature is not the system.

- eg2. We use a table to let items on its surface. One may design a new table with a opening like box, so if you want to let an item on that "new table" you have to open that "boxing feature" to be able to store the item. If you don't know how to use that "new table" you became illiterate and/or boor just because a rich sociopath paid 200.000 programmers and also funded by the governments and supercities to twist table design and advertise that table as "new".

- eg3. Thousands of years of User eXperience can't drop in the cesspit https://www.youtube.com/watch?v=zKK1I2n53pk or read at https://careerfoundry.com/en/blog/ux-design/the-fascinating-history-of-ux-design-a-definitive-timeline/

In this Wikipedia screenshot even Windows 3.1 had the left system menu button.
![Omega-Point win31](https://user-images.githubusercontent.com/18444690/74591537-7d9ff800-5021-11ea-91a3-1a963adb7620.png)

Do you see (or even able to felt) inhumanity in its purpose to design such a "new table", which drops everyday usage of a table? Why those added features had the "tendency" to disable or cripple well established usage? Is it because of [FUD](https://en.wikipedia.org/wiki/Fear,_uncertainty,_and_doubt) malevolence, profit, bias, pure evil or all the above as Eric Dubay indicates?

Alas, your link doesn't bring me anything different. I see youtube _exactly_ like I already see on Mypal and on Centaury. User Agent browser tag is used as before in a malevolent way as another weapon to silence people and push them on certain market (eg. buy/upgrade new computer, learn new bs such as a click is not a click etc.)

I can't believe that Google/Alphabet Inc. aren't able to send me a pure html 4.01 yourube page in case my browser doesn't support new html5 technologies. That browser warring/suggestion on youtube is so ridicule and fake and also happen before too many times. The old whora aren't able to learn new tricks. Yet, those worries around security issues they send on every paid article and webpage is so fake when they monitor everything on everyone.
The screenshot is from 2010 and say in Greek that "the issue have been assigned to a highly trained team of monkeys" so its stingy vile common youtube that piss off and having fun/bulling on people.
![YoutubeMonkeyError](https://user-images.githubusercontent.com/18444690/74593954-92888580-5039-11ea-8854-c4030b474be2.png)
