### ISSUE TITLE
Windows XP, ошибка и вылет.

### ISSUE THREAD

**Issue by saboteur1000** [Feodor2/Centaury#7]
Не работет в вебчатах. Например, https://pruffme.com/
Попробовал его ещё в нескольких чатах и везде одно и то же - после коннекта идёт сообщение об ошибке с последующим вылетом браузера:
http://imglink.ru/show-image.php?id=fe5345fa9fccaea38c5b9b3c4ebeb9d3

**Comment by Feodor2** [comment]
По сайту полазил ошибку не поймал, но и вебчата не нашёл, дайте конкретную ссылку.
Я уже начинаю делать новый выпуск, может сможем починить к его выходу.

**Comment by saboteur1000** [comment]
Эх, там выдавался линк онлайн на платный курс. Сейчас эта ссылка уже не работает.
Попробуйте эти, схема одна и та же: https://chatroulette.com/    https://camki.com/
Было бы круто успеть в апдейт. Мерси!

**Comment by Feodor2** [comment]
Чегото они все стали:
Sorry, your browser does not support current video technology.
Please use Google Chrome.

И ещё у них в гугел много слива, а я его режу.

**Comment by saboteur1000** [comment]
То есть поддержки видео чатов в новом апдейте всё-таки не будет, это конец XP, надо переходить на 7-ку?

**Comment by Feodor2** [comment]
Посмотрим когда будет новая версия, недавно работало, может версию лисы нужно будит подкрутить.
Для хр ещё есть браузер 360 хромой, там эта всё херня должна работать тоже.

**Comment by saboteur1000** [comment]
Круто! Надеюсь на успех!

**Comment by saboteur1000** [comment]
Попробовал 360 extreme explorer, это ужас... Часть меню на китайском. Постоянно вылезают какие-то китайские окошки, на что ни нажмёшь, выкидывает с сайтов. Пришлось снести.

**Comment by Feodor2** [comment]
проверяй
https://mega.nz/file/VO4zQAxL#-mIWleczomGe8WB661sn7lKZhAXHIItdA_x9budHpdI

**Comment by saboteur1000** [comment]
Круто! Спасибо!
Сейчас по-быстрому проверил. Из того, что нашёл:
1. На некоторых вебчатах появляется сообщение:
http://www.imglink.ru/show-image.php?id=b6cce345364d2fd386b2e0d681b26303
2. Гугл почта имеет старинный вид и сообщение, что браузер не поддерживается:
http://imglink.ru/show-image.php?id=1e488c0b25febce63cd31f01572555c2

**Comment by Feodor2** [comment]
1. Ну если конченые эти чатоводы смотрят что за версия то форток, а если линукс то что тогда. Что выше по ссылкам заработали? 
2. В порядке вещей, для гугела можно попробовать притворяться хромым.

**Comment by saboteur1000** [comment]
Да, всё заработало. Спасибо большое за ваш труд и помощь!

**Comment by Feodor2** [comment]
Отлично, буду выкладывать новую версию.

**Comment by saboteur1000** [comment]
Извините, новая версия так и не появилась. Когда планируете?
Спасибо.

**Comment by Feodor2** [comment]
Доделал только что
